### ISSUE TITLE
ens_read_and_verify() fails for some parameters

### ISSUE THREAD

**Issue by mpartio** [andrew-MET/harpPoint#5] opened 2019-09-30 10:12 UTC
Problem:

```
Getting Gmax observations for 201908270000-201909290300

Reading: /nobackup/opdata/verif/HARPresults/OBS/OBSTABLE_2019.sqlite
Lead time: 0 ( Iteration 1 of 19 )
================================================================================
Joining, by = "fcst_model"
Reading: /nobackup/opdata/verif/HARPresults/FCtables//MEPS_prod/2019/08/FCTABLE_Gmax_201908_00+000.sqlite
Reading: /nobackup/opdata/verif/HARPresults/FCtables//MEPS_prod/2019/08/FCTABLE_Gmax_201908_06+000.sqlite
Reading: /nobackup/opdata/verif/HARPresults/FCtables//MEPS_prod/2019/08/FCTABLE_Gmax_201908_12+000.sqlite
Reading: /nobackup/opdata/verif/HARPresults/FCtables//MEPS_prod/2019/08/FCTABLE_Gmax_201908_18+000.sqlite
Reading: /nobackup/opdata/verif/HARPresults/FCtables//MEPS_prod/2019/09/FCTABLE_Gmax_201909_00+000.sqlite
Reading: /nobackup/opdata/verif/HARPresults/FCtables//MEPS_prod/2019/09/FCTABLE_Gmax_201909_06+000.sqlite
Reading: /nobackup/opdata/verif/HARPresults/FCtables//MEPS_prod/2019/09/FCTABLE_Gmax_201909_12+000.sqlite
Reading: /nobackup/opdata/verif/HARPresults/FCtables//MEPS_prod/2019/09/FCTABLE_Gmax_201909_18+000.sqlite
Reading: /nobackup/opdata/verif/HARPresults/FCtables//IFSENS/2019/08/FCTABLE_Gmax_201908_00+000.sqlite
Warning: Units for Gmax GUESSED to be m/s. You can change units by calling set_units.
Reading: /nobackup/opdata/verif/HARPresults/FCtables//IFSENS/2019/08/FCTABLE_Gmax_201908_06+000.sqlite
Warning: Units for Gmax GUESSED to be m/s. You can change units by calling set_units.
Reading: /nobackup/opdata/verif/HARPresults/FCtables//IFSENS/2019/08/FCTABLE_Gmax_201908_12+000.sqlite
Warning: Units for Gmax GUESSED to be m/s. You can change units by calling set_units.
Reading: /nobackup/opdata/verif/HARPresults/FCtables//IFSENS/2019/08/FCTABLE_Gmax_201908_18+000.sqlite
Warning: Units for Gmax GUESSED to be m/s. You can change units by calling set_units.
Reading: /nobackup/opdata/verif/HARPresults/FCtables//IFSENS/2019/09/FCTABLE_Gmax_201909_00+000.sqlite
Warning: Units for Gmax GUESSED to be m/s. You can change units by calling set_units.
Reading: /nobackup/opdata/verif/HARPresults/FCtables//IFSENS/2019/09/FCTABLE_Gmax_201909_06+000.sqlite
Warning: Units for Gmax GUESSED to be m/s. You can change units by calling set_units.
Reading: /nobackup/opdata/verif/HARPresults/FCtables//IFSENS/2019/09/FCTABLE_Gmax_201909_12+000.sqlite
Warning: Units for Gmax GUESSED to be m/s. You can change units by calling set_units.
Reading: /nobackup/opdata/verif/HARPresults/FCtables//IFSENS/2019/09/FCTABLE_Gmax_201909_18+000.sqlite
Warning: Units for Gmax GUESSED to be m/s. You can change units by calling set_units.
Joining, by = c("SID", "validdate", "units")
Joining, by = c("SID", "validdate", "units")
Error in fcprob(as.matrix(eps), thresholds) : 
  Not compatible with requested type: [type=character; target=double].
Calls: ens_read_and_verify ... dots_values -> harp_probs -> %>% -> eval -> eval -> fcprob
Execution halted
```

This happens with S10m, RH2m, Gmax, but not with Pmsl, T2m, CClow, CCtot, AccPcp3h, vis.

Version:

```
[1] harpPoint_0.0.0.9072
```

**Comment by andrew-MET** [comment] 2019-10-02 13:45
Duplicate of #6

**Closed by andrew-MET** 2019-10-02 13:45 UTC
